server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/permmy/springcloudconfigurationstore/src
          username: gathangaperminus@gmail.com
          passphrase: Pbluz6480
